version: '3.8'

services:
  backend:
    build: .
    container_name: accountgpt-scrape
    restart: always
    ports:
      - "8001:8001"  
    networks:
      - "redis"

  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=accountgpt
      - POSTGRES_USER=accountgpt
      - POSTGRES_PASSWORD=accountgpt
    networks:
      - "redis"

  redis:
    image: redis:latest
    ports:
      - "6380:6379" 
    networks:
      - "redis"

networks:
  redis:
    external: true

  
