version: '3.8'

services:
  backend:
    build: .
    container_name: scraping-pipeline
    restart: always
    ports:
      - "8000:8000"  

  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=accountgpt
      - POSTGRES_USER=accountgpt
      - POSTGRES_PASSWORD=accountgpt

  redis:
    image: redis:latest
    ports:
      - "6380:6379" 

  
